### ISSUE TITLE
[BUG]: about Software ver.

### ISSUE THREAD

**Issue by yonderehco1197** [ZL-Audio/ZLEqualizer#102]
### What happened?

```markdown
- Plugin version: 0.3.5 (Software)

Hi!

Sowtware version turned out to be much more productive in my case. Completely gone are the freezes when moving the plugin window/ EQ points and in general the interface is much more responsive.  
Still retained: 
- Delay when moving EQ points (barely noticeable at moderate movement speed).
- FPS drop of the analyzer when moving EQ points.
- Analyzer freezes when opening the very first instance of the plugin (disappears as soon as the JUCE logo disappears).
- Delay when scrolling the UI tab. 
The last two points are not critical in my opinion, while the first two may complicate usability a bit.

Thanks! I hope you can include similar versions in the next updates :)
```

### Additional information

```markdown
- Operating system (& version is applicable): Windows 10 22H2
- DAW: Studio One 6.6.0
```

**Comment by zsliu98** [comment]
> - Delay when moving EQ points (barely noticeable at moderate movement speed).
> - FPS drop of the analyzer when moving EQ points.

Those are expected issues, especially on the software renderer version. Since software renderer is (almost) always slower than hardware renderer, I am afraid there does not exist an easy solution.

> - Analyzer freezes when opening the very first instance of the plugin

I forgot to remove that logo. I will remove it in the next version.

> - Delay when scrolling the UI tab.

Yes, scrolling is very heavy on rendering cause it has to re-render almost everything. I may use tabs to replace scrolling.

> I hope you can include similar versions in the next updates :)

I will. But I would also suggest trying out the hardware version first. I still don't know why Direct2D is so terrible on some Windows machines. Perhaps a future JUCE version will solve this issue.

**Comment by zsliu98** [comment]
A quick update: I have just removed the JUCE logo and updated the installer `ZL.Equalizer-0.3.5-Windows-Software.exe
`.
