### ISSUE TITLE
[BUG]: FL STUDIO 24 Crashes

### ISSUE THREAD

**Issue by KevinValentin0** [ZL-Audio/ZLEqualizer#112]
### Thanks for taking the time to fill out this bug report!

- [X] I have read the plugin manual and searched the existing issues.

### What happened?

```markdown
- Plugin version & format:
- A clear and concise description of what the bug is:
- A clear and concise description of what you expected to happen:
Initially the plugin loads and looks like it is working. Then, sometime later, FL Studio generates an error.
```

### Additional information

```markdown
- Operating system (& version if applicable):
- Hardware (CPU & GPU if applicable):
- DAW:
Windows 11
3.0 GHZ AMD Radeon
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by zsliu98** [comment]
Thanks for reporting. However, cause there have been lots of changes since the last version, could you please try the newest installer in the attachment? (I assume that you are using VST3 and the hardware version). Does it still crash your DAW? If so, could you please provide the error information given by your DAW or OS?
[ZL Equalizer-0.3.5-Windows.exe.zip](https://github.com/user-attachments/files/17263798/ZL.Equalizer-0.3.5-Windows.exe.zip)


Notice: new features listed under the version 0.4.0 in [CHANGELOG](https://github.com/ZL-Audio/ZLEqualizer/blob/main/CHANGELOG.md) have not been fully tested.

**Comment by zsliu98** [comment]
No response in two weeks.
