### ISSUE TITLE
[FR]: UI colour presets

### ISSUE THREAD

**Issue by therealfumbles** [ZL-Audio/ZLEqualizer#119]
### Thanks for taking the time to make a feature request!

- [X] I have read the plugin manual and searched the existing issues.

### Why?

```markdown
As the previous light/dark option was replaced with the ability to customise all the colours, I think it would be a nice addition to have a preset menu there that can store saved UI colours.
```

### What do you want?

```markdown
A preset menu in the UI panel.

As a starting point you could include the default dark theme and perhaps also include the old light theme as well.
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by zsliu98** [comment]
In general, it is a good idea. Ideally, the UI colors can even be shared across different plugins (like ZL Equalizer and ZL Splitter). However, adding a preset system is a relatively large workload. Since EQ matching will include something similar (as we need to save/load target EQ curves), I will look into it after EQ matching (and #108 might also be related). Keep this open to remind me of this.

**Comment by zsliu98** [comment]
Easier than I though. Added in f7978d8445bdc19e31e2f76426c00c75f3234021. I may change the placement of the import/export buttons in the formal release.
