### ISSUE TITLE
[FR]: familiar operation of the value editor/reset to default state

### ISSUE THREAD

**Issue by yonderehco1197** [ZL-Audio/ZLEqualizer#122]
### Thanks for taking the time to make a feature request!

- [X] I have read the plugin manual and searched the existing issues.

### Why?

```markdown
Hi!

The previous principle of working with sliders and value editor was very convenient and intuitive (double click on a slider - reset to default, double click on the current value - its editor). Entering specific values is a more frequent operation than resetting to default, and it is more convenient when it can be done with a simple double click.
```

### What do you want?

```markdown
It would be more logical to assign to Ctrl+click (you can reduce the number of clicks to one) the reset to default, and to double-click - to open the value editor. Thus we get rid of a couple of unnecessary clicks/presses and make the control more unified. The previous hotkeys (double click on slider/editor) were the most convenient.

I feel like I'm missing something very simple and important, but I couldn't find anything in the manual related to this change.

Thanks anyway!
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct.

**Comment by zsliu98** [comment]
The previous hotkeys (in 0.4.1) have some problems:

- for rotary sliders, editors are too close to sliders
- for horizontal sliders, editors are not available
- if you open the editor and mouse leave the area, the label will fail to show up

That's why I use different hotkeys for setting to default/opening the editor. Once #108 is completed, you will be able to customize these hotkeys. Keep this open to remind me.

**Comment by zsliu98** [comment]
Completed b232fcd7a62b544a41714acb74392c4a99921771.
