### ISSUE TITLE
ZLEqualizer and ZLWarm issue

### ISSUE THREAD

**Issue by Nikohaku** [ZL-Audio/ZLEqualizer#24]
Hi, ZLEqualizer and ZLWarm are the only two that don't want to work. I've tried all the others from ZL without any problems.
I have two OSX intel systems, 10.13.6 and 10.15.7.
On both, ZLEqualizer and ZLWarm appear in every DAW in AU format, but they don't open at launch. While in the VST3 format they're not even displayed. I'm sorry because I would have especially wanted to test ZLEqualizer.
Thank you

**Comment by zsliu98** [comment]
ZL Equalizer and ZL Warm are built with a more recent JUCE version on a more recent macOS (provided by Github, which seems to be macOS 12 or macOS 13). Although I specify the building target as macOS 10.13, I am afraid that the whole building process may introduce something that is not compatible with your OS.
I would suggest upgrading your system or building the source on your OS instead.
BTW, since you are on macOS, I should also address that the installer and the plugin have not been notarized.

**Comment by Nikohaku** [comment]
Thanx for your explanation. I'm going to building the source. Yes I know about plugin have not been notarized and I know how to do. Thanx alot

**Comment by zsliu98** [comment]
Hi! If you have time, would you like to check whether the artifact from the [workflow](https://github.com/ZL-Audio/ZLEqualizer/actions/runs/8439522945) is compatible with your OS version (macOS 10.15)? If you cannot access the artifact, please tell me.

**Comment by zsliu98** [comment]
Move to #29
