### ISSUE TITLE
Doesn't work on Windows 7?

### ISSUE THREAD

**Issue by Scorncafe** [ZL-Audio/ZLEqualizer#74]
I get an error when trying to load the plugin, I guess it's only for Windows 10/11? I didn't see specified anywhere so that's why I was wondering

**Comment by zsliu98** [comment]
Yes, it is specified in the manual https://zl-audio.github.io/plugins/zlequalizer/#installation.

The reason is that JUCE 8 only supports Windows 10 and later. If you are on Windows 7, you may `checkout` the `juce7` branch and build the code on your own. However, as JUCE 7 is using software rendering, you may observe worse GUI performance.
